config/routes.rb
Ziogama::Application.routes.draw do

  devise_for :users

  scope "admin" do
    
    resources :sales, :path => "ventas", :only => [:index, :show]

    scope(:path_names => { :new => "nuevo", :edit => "editar" }) do
      resources :prospects, :path => "prospectos"
      resources :users, :path => "usuarios"
      resources :appointments, :path => "citas" do
        member do
           put 'finish'
        end
      end
    end

  end

  root :to => "prospects#index"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :company, :details, :finished_at, :status, :user_id
  belongs_to :user

  before_create :update_status


  def self.chart_data(start = 1.weeks.ago)
	  total_prices = appointments_by_day(start)
	  (start.to_date..Date.today).map do |date|
	    {
	      created_at: date,
	      countdate: total_prices[date] || 0
	    }
	  end
	end

	def self.appointments_by_day(start)
		prospects = where(created_at: start.beginning_of_day..Time.zone.now)
		prospects = group("date(finished_at)").select("finished_at, count(finished_at) as count")
	  prospects.each_with_object({}) do |prospect, argu|
	    argu[prospect.finished_at.to_date] = prospect.count
	  end

	end

  private

  def update_status
  	self.status = false
  	true
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = current_user.appointments.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @appointment = current_user.appointments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = current_user.appointments.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointments_url, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish
    @appointment = Appointment.find(params[:id])

    respond_to do |format|

      if @appointment.update_attributes(:finished_at => DateTime.now, :status => true)
          format.html { redirect_to appointments_url, notice: 'Appointment was successfully updated.' }
          format.json { head :no_content }
      else 
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end

    end

  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
	def state(state)

		if state == true
			content_tag :label, :class => "label label-success" do 
			  "Finalizada"
			end
		else 
			content_tag :label, :class => "label label-important" do 
			  "En Proceso"
			end
		end

	end
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :company %>
    <%= f.input :details %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<div class="page-header">
  <h1>Citas
<%= link_to "Nuevo",
            new_appointment_path,
            :class => 'btn btn-primary pull-right' %>
  </h1>
</div>

<%= content_tag :div, "", id: "graph", data: {orders: current_user.appointments.chart_data} %>

<table class="table table-striped data">
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Inicio</th>
      <th>Final</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.company %></td>
        <td><%= appointment.created_at.try(:strftime, "%Y-%m-%d %H:%M") %></td>
        <td><%= appointment.finished_at.try(:strftime, "%Y-%m-%d %H:%M") %></td>
        <td><%= state(appointment.status) %></td>
        <td>
        
            <%= link_to "Terminar Cita", finish_appointment_path(:id => appointment.id), :method => :put, :disabled => appointment.status?, :class => 'btn btn-info' %>
            <%= link_to 'Ver', appointment, :class => 'btn btn-success' %>
            <%= link_to 'Editar', edit_appointment_path(appointment), :class => 'btn btn-info' %>
            <%= link_to 'Borrar', appointment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @appointment.company %>
</p>

<p>
  <b>User:</b>
  <%= @appointment.user_id %>
</p>

<p>
  <b>Details:</b>
  <%= @appointment.details %>
</p>

<p>
  <b>Finished at:</b>
  <%= @appointment.finished_at %>
</p>

<p>
  <b>Status:</b>
  <%= @appointment.status %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>