config/routes.rb
Ziogama::Application.routes.draw do

  devise_for :users

  scope "admin" do
    
    resources :sales, :path => "ventas", :only => [:index, :show]

    scope(:path_names => { :new => "nuevo", :edit => "editar" }) do
      resources :prospects, :path => "prospectos"
      resources :users, :path => "usuarios"
      resources :appointments, :path => "citas" do
        member do
           put 'finish'
        end
      end
    end

  end

  root :to => "prospects#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ziogama</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar navbar-inverse nav navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Ziogama</a>
			
          	<div class="nav-collapse collapse">
              <ul class="nav">
                  <li class="divider-vertical"></li>
                  <li><a href="/"><i class="icon-home icon-white"></i> Inicio</a></li>

                  
                  <% if can? :manage, User %>  
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Usuarios <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Nuevo", new_user_path %></li>
                        <li><%= link_to "Ver Todos", users_path %></li>
                      </ul>
                  </li>
                  <% end %>
                  <% if current_user.admin? || current_user.sales_manager? %>
                    <li>
                      <%= link_to "Ventas", sales_path %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to "Citas", appointments_path%>
                  </li>
                  
              </ul>
              
              <div class="pull-right">
              	<% if user_signed_in? %>
                <ul class="nav pull-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><% if current_user.avatar? %> <%= image_tag current_user.avatar_url(:thumb).to_s, :class => "profile-img" %> <% end %> Bienvenido, <%= current_user.name %> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/user/preferences"><i class="icon-cog"></i> Preferences</a></li>
                            <li>
                            	<%= link_to destroy_user_session_path, :method => :delete do %>
								  <i class="icon-off"></i> Logout
								<% end %>
                            </li>
                        </ul>
                    </li>
                </ul>
                <% end %>
              </div>
              
            </div>
        </div>
    </div>
</div>

<div class="container">
	<div class="row">
		<div class="span12">
			<% if notice %>
        <p class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </p>
      <% end %>
			<% if alert %>
        <p class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </p>
      <% end %>
			<%= yield %>
		</div>
	</div>
</div>


</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ziogama</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
      <div class="span4 offset4">
        <% if notice %>
          <p class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= notice %>
          </p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= alert %>
          </p>
        <% end %>
        <%= yield %>
      </div>
  </div>
</div>




</body>
</html>